### ISSUE TITLE
BUG | install后，run的时候报下面的错，单独npm install codemirror --save  也没用

### ISSUE THREAD

**Issue by huanzui** [ixrjog/opscloud-web#1]
install后，run的时候报下面的错，单独npm install codemirror --save  也没用

These dependencies were not found:

* codemirror/addon/display/fullscreen.js in ./node_modules/simplemde/src/js/simplemde.js
* codemirror/addon/display/placeholder.js in ./node_modules/simplemde/src/js/simplemde.js
* codemirror/addon/edit/continuelist.js in ./node_modules/simplemde/src/js/simplemde.js
* codemirror/addon/mode/overlay.js in ./node_modules/simplemde/src/js/simplemde.js
* codemirror/addon/selection/mark-selection.js in ./node_modules/simplemde/src/js/simplemde.js
* codemirror/mode/gfm/gfm.js in ./node_modules/simplemde/src/js/simplemde.js
* codemirror/mode/markdown/markdown.js in ./node_modules/simplemde/src/js/simplemde.js
* codemirror/mode/xml/xml.js in ./node_modules/simplemde/src/js/simplemde.js

**Comment by ixrjog** [comment]
这个项目已经不维护了，opscloud4版本前端仓库地址 https://github.com/ixrjog/opscloud4-web

**Comment by huanzui** [comment]
> 

噢 ，不好意思，弄错了 ，这个异常是 [opscloud4-web](https://github.com/ixrjog/opscloud4-web) 报出来的
![image](https://user-images.githubusercontent.com/7300261/177908318-688d17b8-d628-4e25-97dc-99bef02a4c02.png)

**Comment by ixrjog** [comment]
https://d2.pub/zh/doc/d2-admin/learn/start.html#%E4%B8%8B%E8%BD%BD%E9%A1%B9%E7%9B%AE
参考官方文档
换cnpm后执行
```
npm i
```
